### ISSUE TITLE
[Heroku specific] Error: Cannot find module '/app/.bitpay/config.json'

### ISSUE THREAD

**Issue by QuantumInformation** [bitpay/node-bitpay-client#79]
I followed the instructions pretty much to the letter and the client works fine in my local node installation.

However when deploying to Heroku I am getting this error about a missing config

```
: Error: Cannot find module '/app/.bitpay/config.json'
2016-06-02T16:22:24.716365+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-06-02T16:22:24.716366+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-06-02T16:22:24.716367+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-06-02T16:22:24.716367+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-06-02T16:22:24.716368+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/bitpay-rest/lib/rest-client.js:11:20)
```
any ideas, thanks?

maybe there could be a happy fail path if you have the object in client setup..

![image](https://cloud.githubusercontent.com/assets/216566/15756338/b10bf1ac-28f8-11e6-8cd3-99bd1e9c988a.png)

**Comment by QuantumInformation** [comment]
Update, that specific error is gone by me creating a file like so:

![image](https://cloud.githubusercontent.com/assets/216566/15757544/f19918f8-28fd-11e6-95f6-f883e9f4612d.png)
