### ISSUE TITLE
Bitpay-rest not compiling on linux due to bignum

### ISSUE THREAD

**Issue by SuragSheth** [bitpay/node-bitpay-client#90]
On my development server on my mac everything is working properly (It uses node-gyp my dev env to compile code after it fails. ) but when trying to move the code into our staging environment on a linux vm big num refuses to install, and the whole process fails. 

Im running 7.7.1 after my upgrade, ive tried on ver 8 and 6 as well. Anyone have any quick solutions? 

`sudo npm install bitpay-rest --save

bignumÉ0.12.5 install /home/Co1n/node_modules/bignum
node-pre-gyp install --fallback-to-build

> node-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v51-linux-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for bignumÉ0.12.5 and nodeÉ7.7.1 (node-v51 ABI)

 (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.7.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/Co1n/node_modules/bignum/.node-gyp"
make: Entering directory '/home/Co1n/node_modules/bignum/build'
make: *** No rule to make target '../.node-gyp/7.7.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/Co1n/node_modules/bignum/build'
gyp ERR! build error 
gyp ERR! stack Error: émakeé failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/Co1n/node_modules/bignum/binding/bignum.node" "--module_name=bignum" "--module_path=/home/Co1n/node_modules/bignum/binding"
gyp ERR! cwd /home/Co1n/node_modules/bignum
gyp ERR! node -v v7.7.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.j
s build --fallback-to-build --module=/home/Co1n/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/home/Co1n/node
_modules/bignum/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/Co1n/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/Co1n/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/Co1n/node_modules/bignum
node-pre-gyp ERR! node -v v7.7.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --m
odule=/home/Co1n/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/home/Co1n/node_modules/bignum/binding' (1)
HDCryptoÉ /home/Co1n
└── (empty)
npm WARN HDCryptoÉ No description
npm WARN HDCryptoÉ No repository field.
npm WARN HDCryptoÉ No license field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bitpay-rest" "--save"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! bignumÉ0.12.5 install: énode-pre-gyp install --fallback-to-buildé
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignumÉ0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/Co1n/npm-debug.log`

I even tried installing with --unsafe-perm

 ./node_modules/bitpay-rest/bin/bitpay.js keygen

`./node_modules/bitpay-rest/bin/bitpay.js keygen
module.js:472
    throw err;
    Ü
Error: Cannot find module '/home/surag_sheth/.bitpay/config.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/Co1n/node_modules/bitpay-rest/lib/rest-client.js:11:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)`

Please Help, Cheers !

**Comment by kmltrk** [comment]
I hava this error too.
